Homework 4
ozoncp/ocp-classroom-api pull request #1
Opened 2021-05-29 20:34 UTC by MinusNull

Реализовано:
flusher

Добавлено:
Flusher и Repo интерфейсы
Mocks для Repo интерфейса
Тесты для Flusher интерфейса

Отрефакторены:
Classroom
Функция открытия, чтения и закрытия файла

Удален:
Неиспользуемый код в тесте.

2021-06-01 10:26 UTC, xmikasax requested changes

2021-06-01 10:26 UTC, xmikasax commented on internal/flusher/flusher_test.go
> +			mockRepo.EXPECT().AddClassrooms(gomock.Any()).DoAndReturn(
Можно сразу Return. У тебя же нет side effect'ов

2021-06-01 10:26 UTC, xmikasax commented on internal/flusher/flusher.go
> +	if err := fl.repo.AddClassrooms(classrooms); err != nil {
Пока не важно, но думаю, что стоит применить функцию разделения на батчи, которую писали до этого

2021-06-01 21:57 UTC, MinusNull commented on internal/flusher/flusher_test.go
> +			mockRepo.EXPECT().AddClassrooms(gomock.Any()).DoAndReturn(
Да, спасибо.

2021-06-01 21:57 UTC, MinusNull commented on internal/flusher/flusher.go
> +	if err := fl.repo.AddClassrooms(classrooms); err != nil {
Ок, сделал :)

2021-06-02 11:21 UTC, xmikasax approved these changes
Ок

2021-06-02 20:31 UTC, merged