Homework 5
ozoncp/ocp-classroom-api pull request #2
Opened 2021-06-05 09:47 UTC by MinusNull

В пятом домашнем задании сделано:
- Реализован Saver интерфейс с возможностью писать в хранилище данных с определенным интервалом или по закрытию
- Добавлены тесты для Saver
- Отрефакторен main.go
- Добавлена работа с Saver в main.go

2021-06-06 18:24 UTC, xmikasax requested changes

2021-06-06 18:24 UTC, xmikasax commented on internal/saver/saver.go
> +	}
Думаю, что проверки стоит перенести в New, чтобы не было возможности создать объект с некорректными полями

2021-06-06 18:24 UTC, xmikasax commented on internal/saver/saver.go
> +	}
Вот здесь уже можно и панику кинуть. Просто игнорировать данные в функции Save - плохая идея

2021-06-06 18:24 UTC, xmikasax commented on internal/saver/saver.go
> +		close(s.isClosedCh)
Обычно каналы закрывают для управления потоком данных. Просто так закрывать их нет смысла

2021-06-06 18:52 UTC, MinusNull commented on internal/saver/saver.go
> +	}
Если из New возвращают nil, значит не удалось создать объект? Ок!

2021-06-06 18:53 UTC, MinusNull commented on internal/saver/saver.go
> +		close(s.isClosedCh)
Вот здесь не понял.

Их оставить незакрытыми?

2021-06-06 18:54 UTC, MinusNull commented on internal/saver/saver.go
> +		close(s.isClosedCh)
Закрыть только этот канал?

close(s.classroomCh)

А остальные не закрывать? :)

2021-06-07 09:13 UTC, xmikasax commented on internal/saver/saver.go
> +	}
Можно оставить как есть, это просто рекомендация) Если делать проверки в New, то лучше еще вернуть ошибку, а не просто nil

2021-06-07 09:15 UTC, xmikasax commented on internal/saver/saver.go
> +		close(s.isClosedCh)
А зачем тебе здесь закрывать канал? Ты ориентируешься на isInited, я бы ничего не закрыл совсем) (Но не забывай, что такой вариант не thread-safe)

2021-06-08 08:41 UTC, xmikasax approved these changes

2021-06-08 09:27 UTC, merged